name: karakter_aynasi_mobil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Mevcut paketler
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  http_parser: ^4.0.2

  # YORUM: EKLENEN YENİ PAKETLER
  # Uygulama içi satın alma için
  in_app_purchase: ^3.2.0 
  # Reklam gösterimi için
  google_mobile_ads: ^6.0.0
  # PDF indirme ve görüntüleme için
  path_provider: ^2.1.3
  open_file: ^3.3.2
  # Ses çalmak için
  audioplayers: ^6.0.0
  # Yükleme göstergesi için
  flutter_spinkit: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
